// auto-generated/previews/react/textarea.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';

export default () => {
  return <textarea placeholder="Enter text here"></textarea>;
};

// auto-generated/previews/angular/textarea.ts
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <textarea placeholder="Enter text here">
  Some example text
</textarea>
  `,
})
export default class Textarea {}
