// packages/vue-test-app/src/preview-examples/toggle-button-secondary.vue
<!--
SPDX-FileCopyrightText: 2023 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxToggleButton } from '@siemens/ix-vue';
</script>

<style scoped src="../../../styles/toggle-button.css"></style>

<template>
  <IxToggleButton>Normal</IxToggleButton>
  <IxToggleButton pressed>Pressed</IxToggleButton>
  <IxToggleButton disabled>Disabled</IxToggleButton>
  <IxToggleButton disabled loading>Loading</IxToggleButton>
</template>

// demo/v2/react/toggle-button-secondary.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './toggle-button-secondary.scoped.css';

import { IxToggleButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxToggleButton>Normal</IxToggleButton>
      <IxToggleButton pressed>Pressed</IxToggleButton>
      <IxToggleButton disabled>Disabled</IxToggleButton>
      <IxToggleButton disabled loading>
        Loading
      </IxToggleButton>
    </>
  );
};
