// packages/react-test-app/src/preview-examples/number-input-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberInput } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxNumberInput disabled></IxNumberInput>
    </>
  );
};

// v6.0.0/examples/vue/number-input-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberInput } from '@siemens/ix-vue';
</script>

<template>
  <IxNumberInput disabled></IxNumberInput>
</template>
