// v5.2.1/examples/vue/tabs-overflow.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * Overflow case: same as Storybook Example/Tabs → Overflow (340px, 8 tabs).
-->

<script setup lang="ts">
import { IxTabItem, IxTabs } from '@siemens/ix-vue';
import { ref } from 'vue';

const OVERFLOW_TABS = [
  { tabKey: 'overview', label: 'Overview' },
  { tabKey: 'analytics', label: 'Analytics' },
  { tabKey: 'events', label: 'Events' },
  { tabKey: 'automation', label: 'Automation' },
  { tabKey: 'data-sources', label: 'Data Sources' },
  { tabKey: 'notifications', label: 'Notifications' },
  { tabKey: 'history', label: 'History' },
  { tabKey: 'settings', label: 'Settings' },
];

const activeTabKey = ref('overview');

const setActiveTabKey = (event: CustomEvent<string | undefined>) => {
  activeTabKey.value = event.detail ?? 'overview';
};
</script>

<style scoped src="./tabs.css"></style>

<template>
  <div class="tabs" :style="{ maxWidth: '340px' }">
    <IxTabs
      :activeTabKey="activeTabKey"
      layout="auto"
      @tabChange="setActiveTabKey"
    >
      <IxTabItem
        v-for="{ tabKey, label } in OVERFLOW_TABS"
        :key="tabKey"
        :tabKey="tabKey"
      >
        {{ label }}
      </IxTabItem>
    </IxTabs>
    <section role="tabpanel" aria-label="Example content">
      Content
      {{ OVERFLOW_TABS.find((tab) => tab.tabKey === activeTabKey)?.label }}
    </section>
  </div>
</template>

// examples/angular-standalone-examples/src/preview-examples/tabs-overflow.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * Overflow case: same as Storybook Example/Tabs → Overflow (340px, 8 tabs).
 */

import { Component } from '@angular/core';
import { IxTabs, IxTabItem } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxTabs, IxTabItem],
  template: `
    <div class="tabs" style="max-width: 340px;">
      <ix-tabs
        [activeTabKey]="activeTabKey"
        layout="auto"
        (tabChange)="activeTabKey = $event.detail ?? 'overview'"
      >
        <ix-tab-item tabKey="overview">Overview</ix-tab-item>
        <ix-tab-item tabKey="analytics">Analytics</ix-tab-item>
        <ix-tab-item tabKey="events">Events</ix-tab-item>
        <ix-tab-item tabKey="automation">Automation</ix-tab-item>
        <ix-tab-item tabKey="data-sources">Data Sources</ix-tab-item>
        <ix-tab-item tabKey="notifications">Notifications</ix-tab-item>
        <ix-tab-item tabKey="history">History</ix-tab-item>
        <ix-tab-item tabKey="settings">Settings</ix-tab-item>
      </ix-tabs>
      <section role="tabpanel" aria-label="Example content">
        @switch (activeTabKey) { @case ('overview') { Content Overview } @case
        ('analytics') { Content Analytics } @case ('events') { Content Events }
        @case ('automation') { Content Automation } @case ('data-sources') {
        Content Data Sources } @case ('notifications') { Content Notifications }
        @case ('history') { Content History } @case ('settings') { Content
        Settings } }
      </section>
    </div>
  `,
  styleUrls: ['./tabs.css'],
})
export default class TabsOverflow {
  activeTabKey = 'overview';
}
