// examples/react-examples/src/preview-examples/textarea-legacy.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */



export default () => {
  return <textarea placeholder="Enter text here"></textarea>;
};

// examples/angular-standalone-examples/src/preview-examples/textarea-legacy.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: ` <textarea placeholder="Enter text here"></textarea> `,
})
export default class TextareaLegacy {}
