// packages/react-test-app/src/preview-examples/datetime-input-label.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDatetimeInput } from '@siemens/ix-react';

function DatetimeInputLabel() {
  return (
    <IxDatetimeInput
      value="08.02.2026 00:00"
      label="Meeting schedule"
      format="dd.MM.yyyy HH:mm"
    ></IxDatetimeInput>
  );
}

export default DatetimeInputLabel;

// examples/angular-examples/src/preview-examples/datetime-input-label.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './datetime-input-label.html',
})
export default class DatetimeInputLabel {}
