// packages/vue-test-app/src/preview-examples/action-card.vue
<!--
SPDX-FileCopyrightText: 2023 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxActionCard } from '@siemens/ix-vue';

const onClick = (event: Event) => {
  console.log(event);
};
</script>

<template>
  <IxActionCard
    icon="refresh"
    heading="Scan for new devices"
    subheading="Secondary text"
    variant="insight"
    @click="onClick"
  ></IxActionCard>
</template>

// version-dev/auto-generated/previews/react/action-card.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxActionCard } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <IxActionCard
      icon="refresh"
      heading="Scan for new devices"
      subheading="Secondary text"
      variant="insight"
      onClick={console.log}
    ></IxActionCard>
  );
};
