// examples/vue-examples/src/preview-examples/upload.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxUpload } from '@siemens/ix-vue';
</script>

<template>
  <IxUpload />
</template>

// version-dev/auto-generated/previews/react/upload.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxUpload } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return <IxUpload />;
};
