// examples/vue-examples/src/preview-examples/number-input-readonly.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberInput } from '@siemens/ix-vue';
</script>

<template>
  <IxNumberInput readonly></IxNumberInput>
</template>

// feat/block-cli/examples/react-examples/src/preview-examples/number-input-readonly.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberInput } from '@siemens/ix-react';

export default () => {
  return <IxNumberInput readonly></IxNumberInput>;
};
