// packages/react-test-app/src/preview-examples/buttons.tsx
/*
 * SPDX-FileCopyrightText: 2022 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxButton } from '@siemens/ix-react';
import React from 'react';

export const Buttons: React.FC = () => {
  return (
    <>
      <IxButton className="m-1" variant="Primary">
        Button
      </IxButton>
      <IxButton className="m-1" variant="Primary" disabled>
        Button
      </IxButton>
    </>
  );
};

// auto-generated/previews/vue/buttons.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton } from '@siemens/ix-vue';
</script>

<template>
  <IxButton className="m-1" variant="primary"> Button </IxButton>
  <IxButton className="m-1" variant="primary" disabled> Button </IxButton>
</template>
