// version-dev/auto-generated/previews/react/checkbox-indeterminate.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useLayoutEffect, useRef } from 'react';

export default () => {
  const ref = useRef<HTMLInputElement>(null);

  useLayoutEffect(() => {
    const element = ref.current;

    if (element) {
      element.indeterminate = true;
    }
  }, []);

  return (
    <>
      <input type="checkbox" id="checkbox_01" ref={ref} />
      <label htmlFor="checkbox_01">Simple checkbox</label>
    </>
  );
};

// auto-generated/previews/vue/checkbox-indeterminate.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { onMounted, ref } from 'vue';

const input = ref<HTMLInputElement>();

onMounted(() => {
  const element = input.value;
  if (element) element.indeterminate = true;
});
</script>

<template>
  <input type="checkbox" id="checkbox_01" ref="input" />
  <label htmlFor="checkbox_01">Simple checkbox</label>
</template>
