// version-dev/auto-generated/previews/react/event-list-custom-item-height.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxEventList, IxEventListItem } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <IxEventList itemHeight={'L'}>
      <IxEventListItem color="color-primary">Text 1</IxEventListItem>
      <IxEventListItem color="color-primary">Text 2</IxEventListItem>
      <IxEventListItem color="color-primary">Text 3</IxEventListItem>
      <IxEventListItem color="color-primary">Text 4</IxEventListItem>
    </IxEventList>
  );
};

// auto-generated/previews/vue/event-list-custom-item-height.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxEventList, IxEventListItem } from '@siemens/ix-vue';
</script>

<template>
  <IxEventList itemHeight="L">
    <IxEventListItem color="color-primary">Text 1</IxEventListItem>
    <IxEventListItem color="color-primary">Text 2</IxEventListItem>
    <IxEventListItem color="color-primary">Text 3</IxEventListItem>
    <IxEventListItem color="color-primary">Text 4</IxEventListItem>
  </IxEventList>
</template>
