// examples/react-examples/src/preview-examples/textarea-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTextarea } from '@siemens/ix-react';

export default () => {
  return <IxTextarea value="Some text" disabled></IxTextarea>;
};

// auto-generated/previews/vue/textarea-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script lang="ts">
import { IxTextarea } from '@siemens/ix-vue';

export default {
  name: 'TextareaDisabled',
  components: { IxTextarea },
};
</script>

<template>
  <IxTextarea
    value="Some text"
    disabled
  ></IxTextarea>
</template>
