// packages/ix-documentation/static/auto-generated/previews/react/toggle.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle } from '@siemens/ix-react';

export default () => {
  return <IxToggle />;
};

// auto-generated/previews/vue/toggle.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxToggle } from '@siemens/ix-vue';
</script>

<template>
  <IxToggle />
</template>
