// version-2.7/auto-generated/previews/react/avatar.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxAvatar } from '@siemens/ix-react';

export default () => {
  return <IxAvatar></IxAvatar>;
};

// packages/vue-test-app/src/preview-examples/avatar.vue
<!--
SPDX-FileCopyrightText: 2023 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxAvatar } from '@siemens/ix-vue';
</script>

<template>
  <IxAvatar></IxAvatar>
</template>
