// packages/react-test-app/src/preview-examples/date-picker-require-confirmation.tsx
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './date-picker-require-confirmation.scoped.css';

import { IxDatePicker, IxToggle, IxTypography } from '@siemens/ix-react';
import { useState } from 'react';

const descriptions = {
  off: 'dateChange and dateRangeChange are emitted for every picked date.',
  on: 'dateChange and dateRangeChange are emitted only when you click Confirm. Cancel discards the picked dates and emits dateCancel.',
};

export default () => {
  const [requireConfirmation, setRequireConfirmation] = useState(false);
  const [events, setEvents] = useState<string[]>([]);

  const log = (name: string, detail: unknown) =>
    setEvents((previous) =>
      [`${name}: ${JSON.stringify(detail) ?? ''}`, ...previous].slice(0, 5)
    );

  return (
    <div className="require-confirmation">
      <IxToggle
        aria-label="Require confirmation"
        textOn="Require confirmation: on"
        textOff="Require confirmation: off"
        checked={requireConfirmation}
        onCheckedChange={(event) => {
          setRequireConfirmation(event.detail);
          setEvents([]);
        }}
      />
      <IxTypography>
        {requireConfirmation ? descriptions.on : descriptions.off}
      </IxTypography>
      <IxDatePicker
        from="2026/10/05"
        to="2026/10/09"
        requireConfirmation={requireConfirmation}
        onDateChange={(event) => log('dateChange', event.detail)}
        onDateRangeChange={(event) => log('dateRangeChange', event.detail)}
        onDateSelect={(event) => log('dateSelect', event.detail)}
        onDateCancel={(event) => log('dateCancel', event.detail)}
      />
      <IxTypography format="label">Emitted events (latest first)</IxTypography>
      <ul className="event-log">
        {events.map((event, index) => (
          <li key={index}>{event}</li>
        ))}
      </ul>
    </div>
  );
};

// packages/vue-test-app/src/preview-examples/date-picker-require-confirmation.vue
<!--
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxDatePicker, IxToggle, IxTypography } from '@siemens/ix-vue';
import { ref } from 'vue';

const descriptions = {
  off: 'dateChange and dateRangeChange are emitted for every picked date.',
  on: 'dateChange and dateRangeChange are emitted only when you click Confirm. Cancel discards the picked dates and emits dateCancel.',
};

const requireConfirmation = ref(false);
const events = ref<string[]>([]);

const onCheckedChange = (event: CustomEvent<boolean>) => {
  requireConfirmation.value = event.detail;
  events.value = [];
};

const log = (name: string, event: CustomEvent<unknown>) => {
  const detail = JSON.stringify(event.detail) ?? '';
  events.value = [`${name}: ${detail}`, ...events.value].slice(0, 5);
};
</script>

<style scoped src="./date-picker-require-confirmation.css"></style>

<template>
  <div class="require-confirmation">
    <IxToggle
      aria-label="Require confirmation"
      text-on="Require confirmation: on"
      text-off="Require confirmation: off"
      :checked="requireConfirmation"
      @checkedChange="onCheckedChange"
    />
    <IxTypography>
      {{ requireConfirmation ? descriptions.on : descriptions.off }}
    </IxTypography>
    <IxDatePicker
      from="2026/10/05"
      to="2026/10/09"
      :requireConfirmation="requireConfirmation"
      @dateChange="log('dateChange', $event)"
      @dateRangeChange="log('dateRangeChange', $event)"
      @dateSelect="log('dateSelect', $event)"
      @dateCancel="log('dateCancel', $event)"
    />
    <IxTypography format="label">Emitted events (latest first)</IxTypography>
    <ul class="event-log">
      <li v-for="(event, index) in events" :key="index">{{ event }}</li>
    </ul>
  </div>
</template>
