// packages/react-test-app/src/preview-examples/link-button.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxLinkButton } from '@siemens/ix-react';


export default () => {
  return <IxLinkButton url="https://ix.siemens.io/">Link text</IxLinkButton>;
};

// packages/vue-test-app/src/preview-examples/link-button.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxLinkButton } from '@siemens/ix-vue';
</script>

<template>
  <IxLinkButton url="https://ix.siemens.io/">Link text</IxLinkButton>
</template>
