// demo/v2/react/toggle-button-secondary-ghost.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './toggle-button-secondary-ghost.scoped.css';

import { IxToggleButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxToggleButton ghost>Normal</IxToggleButton>
      <IxToggleButton ghost pressed>
        Pressed
      </IxToggleButton>
      <IxToggleButton ghost disabled>
        Disabled
      </IxToggleButton>
      <IxToggleButton ghost disabled loading>
        Loading
      </IxToggleButton>
    </>
  );
};

// packages/vue-test-app/src/preview-examples/toggle-button-secondary-ghost.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxToggleButton } from '@siemens/ix-vue';
</script>

<template>
  <IxToggleButton className="m-1" ghost>Normal</IxToggleButton>
  <IxToggleButton className="m-1" ghost pressed>Pressed</IxToggleButton>
  <IxToggleButton className="m-1" ghost disabled>Disabled</IxToggleButton>
  <IxToggleButton className="m-1" ghost disabled loading>Loading</IxToggleButton>
</template>
