// examples/vue-examples/src/preview-examples/badge-counter.vue
<!--
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxBadge } from '@siemens/ix-vue';
</script>

<style scoped src="./badge-counter.css"></style>

<template>
  <div class="container">
    <IxBadge type="counter" label="8" variant="primary"></IxBadge>
    <IxBadge type="counter" label="8" variant="primary" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="primary" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="primary" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="alarm"></IxBadge>
    <IxBadge type="counter" label="8" variant="alarm" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="alarm" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="alarm" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="critical"></IxBadge>
    <IxBadge type="counter" label="8" variant="critical" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="critical" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="critical" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="warning"></IxBadge>
    <IxBadge type="counter" label="8" variant="warning" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="warning" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="warning" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="info"></IxBadge>
    <IxBadge type="counter" label="8" variant="info" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="info" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="info" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="neutral"></IxBadge>
    <IxBadge type="counter" label="8" variant="neutral" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="neutral" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="neutral" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="success"></IxBadge>
    <IxBadge type="counter" label="8" variant="success" outline></IxBadge>
    <IxBadge type="counter" label="8" variant="success" enable-animation></IxBadge>
    <IxBadge type="counter" label="8" variant="success" outline enable-animation></IxBadge>

    <IxBadge type="counter" label="8" variant="custom" background="var(--theme-chart-11)" badge-color="var(--theme-color-inv-std-text)"></IxBadge>
    <IxBadge type="counter" label="8" variant="custom" outline background="var(--theme-chart-11)" badge-color="var(--theme-chip-outline--color)"></IxBadge>
    <IxBadge type="counter" label="8" variant="custom" enable-animation background="var(--theme-chart-11)" badge-color="var(--theme-color-inv-std-text)"></IxBadge>
    <IxBadge type="counter" label="8" variant="custom" outline enable-animation background="var(--theme-chart-11)" badge-color="var(--theme-chip-outline--color)"></IxBadge>

  </div>
</template>

// packages/angular-standalone-test-app/src/preview-examples/badge-counter.ts
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxBadge } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxBadge],
  styleUrls: ['./badge-counter.css'],
  template: `
    <div class="container">
      <ix-badge type="counter" label="8" variant="primary"></ix-badge>
      <ix-badge type="counter" label="8" variant="primary" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="primary" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="primary" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="alarm"></ix-badge>
      <ix-badge type="counter" label="8" variant="alarm" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="alarm" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="alarm" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="critical"></ix-badge>
      <ix-badge type="counter" label="8" variant="critical" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="critical" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="critical" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="warning"></ix-badge>
      <ix-badge type="counter" label="8" variant="warning" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="warning" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="warning" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="info"></ix-badge>
      <ix-badge type="counter" label="8" variant="info" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="info" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="info" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="neutral"></ix-badge>
      <ix-badge type="counter" label="8" variant="neutral" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="neutral" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="neutral" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="success"></ix-badge>
      <ix-badge type="counter" label="8" variant="success" outline></ix-badge>
      <ix-badge type="counter" label="8" variant="success" enable-animation></ix-badge>
      <ix-badge type="counter" label="8" variant="success" outline enable-animation></ix-badge>

      <ix-badge type="counter" label="8" variant="custom" background="var(--theme-chart-11)" badge-color="var(--theme-color-inv-std-text)"></ix-badge>
      <ix-badge type="counter" label="8" variant="custom" outline background="var(--theme-chart-11)" badge-color="var(--theme-chip-outline--color)"></ix-badge>
      <ix-badge type="counter" label="8" variant="custom" enable-animation background="var(--theme-chart-11)" badge-color="var(--theme-color-inv-std-text)"></ix-badge>
      <ix-badge type="counter" label="8" variant="custom" outline enable-animation background="var(--theme-chart-11)" badge-color="var(--theme-chip-outline--color)"></ix-badge>

    </div>
  `,
})
export default class BadgeCounter {}
