// examples/react-examples/src/preview-examples/datetime-range.tsx
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDatetimeInput, IxRangeField } from '@siemens/ix-react';

export default () => {
  return (
    <IxRangeField
      type="datetime-range"
      style={{ width: '32rem' }}
      aria-label="Datetime range"
    >
      <IxDatetimeInput label="Start date and time"></IxDatetimeInput>
      <IxDatetimeInput label="End date and time"></IxDatetimeInput>
    </IxRangeField>
  );
};

// packages/angular-standalone-test-app/src/preview-examples/datetime-range.ts
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxDatetimeInput, IxRangeField } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxRangeField, IxDatetimeInput],
  template: `
    <ix-range-field type="datetime-range" style="width: 32rem" aria-label="Datetime range">
      <ix-datetime-input label="Start date and time"></ix-datetime-input>
      <ix-datetime-input label="End date and time"></ix-datetime-input>
    </ix-range-field>
  `,
})
export default class DatetimeRange {}
