// packages/vue-test-app/src/preview-examples/input-legacy-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts"></script>

<template>
  <form className="needs-validation">
    <input
      value="Some example text"
      placeholder="Enter text here"
      type="text"
      disabled
    />
  </form>
</template>

// packages/angular-standalone-test-app/src/preview-examples/input-legacy-disabled.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <form class="needs-validation">
      <input
        value="Some example text"
        placeholder="Enter text here"
        type="text"
        disabled
      />
    </form>
  `,
})
export default class InputLegacyDisabled {}
