// main/examples/react/toggle-custom-label.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle } from '@siemens/ix-react';

export default () => {
  return <IxToggle textOff="Offline" textOn="Online" aria-label="Connection status"></IxToggle>;
};

// packages/angular-standalone-test-app/src/preview-examples/toggle-custom-label.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxToggle,
  IxBooleanValueAccessorDirective,
} from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxToggle, IxBooleanValueAccessorDirective],
  template: ` <ix-toggle textOff="Offline" textOn="Online" aria-label="Connection status"></ix-toggle> `,
})
export default class ToggleCustomLabel {}
