// examples/react-examples/src/preview-examples/textarea-legacy-readonly.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export default () => {
  return (
    <textarea placeholder="Enter text here" readOnly>
      Some example text
    </textarea>
  );
};

// feat/block-cli/examples/vue-examples/src/preview-examples/textarea-legacy-readonly.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts"></script>

<template>
  <textarea placeholder="Enter text here" readOnly>Some example text</textarea>
</template>
