// packages/react-test-app/src/preview-examples/button-grey.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import 'example-styles/dist/buttons.css';

import { IxButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="secondary">Button</IxButton>
      <IxButton disabled variant="secondary">
        Button
      </IxButton>
    </>
  );
};

// packages/angular-test-app/src/preview-examples/button-grey.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <ix-button variant="secondary"> Button </ix-button>
    <ix-button disabled variant="secondary"> Button </ix-button>
  `,
  styles: [
    `
      @import 'example-styles/dist/buttons.css';
    `,
  ],
})
export default class Buttons {}
