// packages/vue-test-app/src/preview-examples/number-field-validation.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberField } from '@siemens/ix-vue';
</script>

<template>
  <div>
    <IxNumberField
      :value="5"
      info-text="Info text"
      class="ix-info"
    ></IxNumberField>
  </div>

  <div>
    <IxNumberField
      :value="5"
      warning-text="Warning text"
      class="ix-warning"
    ></IxNumberField>
  </div>

  <div>
    <IxNumberField
      :value="5"
      valid-text="Valid text"
      class="ix-valid"
    ></IxNumberField>
  </div>

  <div>
    <IxNumberField
      :value="5"
      invalid-text="Invalid text"
      class="ix-invalid"
    ></IxNumberField>
  </div>
</template>

// packages/angular-test-app/src/preview-examples/number-field-validation.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  templateUrl: './number-field-validation.html'
})
export default class NumberFieldValidation {}
