// packages/react-test-app/src/preview-examples/page-header.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { IxButton, IxIconButton, IxPageHeader } from '@siemens/ix-react';

import React from 'react';

export default () => {
  return (
    <>
      <IxPageHeader
        has-back-button
        header-title="content title"
        header-subtitle="subtitle content"
      >
        <IxButton ghost>Button1</IxButton>
        <IxButton ghost>Button2</IxButton>
        <IxButton ghost>Button3</IxButton>
      </IxPageHeader>
      <IxPageHeader
        variant="Secondary"
        header-title="content title"
        header-subtitle="subtitle content"
      >
        <IxIconButton icon="pen" ghost variant="Primary">
          Button1
        </IxIconButton>
        <IxIconButton icon="trashcan" ghost variant="Primary">
          Button2
        </IxIconButton>
        <IxIconButton icon="context-menu" ghost variant="Primary">
          Button3
        </IxIconButton>
      </IxPageHeader>
    </>
  );
};

// packages/angular-test-app/src/preview-examples/page-header.ts
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <ix-page-header
      hasBackButton="true"
      headerTitle="content title"
      headerSubtitle="subtitle content"
    >
      <ix-button ghost="true">Button1</ix-button>
      <ix-button ghost="true">Button2</ix-button>
      <ix-button ghost="true">Button3</ix-button>
    </ix-page-header>
    <ix-page-header
      variant="Secondary"
      headerTitle="content title"
      headerSubtitle="subtitle content"
    >
      <ix-icon-button icon="pen" ghost="true" variant="Primary">
        Button1
      </ix-icon-button>
      <ix-icon-button icon="trashcan" ghost="true" variant="Primary">
        Button2
      </ix-icon-button>
      <ix-icon-button icon="context-menu" ghost="true" variant="Primary">
        Button3
      </ix-icon-button>
    </ix-page-header>
  `,
})
export default class PageHeader {}
