// packages/vue-test-app/src/preview-examples/textarea-field-validation.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script lang='ts'>
import { IxTextareaField } from '@siemens/ix-vue';

export default {
  name: 'TextareaField',
  components: { IxTextareaField },
};
</script>

<template>
  <div>
    <IxTextareaField
      :max-length="100"
      name="comment"
      label="Comment"
      info-text="Info text"
      class="ix-info"
    ></IxTextareaField>
  </div>

  <div>
    <IxTextareaField
      :max-length="100"
      name="comment"
      label="Comment"
      warning-text="Warning text"
      class="ix-warning"
    ></IxTextareaField>
  </div>

  <div>
    <IxTextareaField
      :max-length="100"
      name="comment"
      label="Comment"
      valid-text="Valid text"
      class="valid"
    ></IxTextareaField>
  </div>

  <div>
    <IxTextareaField
      :max-length="100"
      name="comment"
      label="Comment"
      invalid-text="Invalid text"
      class="ix-invalid"
    ></IxTextareaField>
  </div>
</template>

// packages/angular-test-app/src/preview-examples/textarea-field-validation.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  templateUrl: './textarea-field-validation.html',
})
export default class TextareaFieldValidation {
}
