// packages/vue-test-app/src/preview-examples/time-input-form-test.vue
<!--
SPDX-FileCopyrightText: 2024 Siemens AG

SPDX-License-Identifier: MIT

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
-->

<template>
  <div style="padding: 1rem; font-size: 0.9rem">
    <h2 style="margin-bottom: 0.5rem">Time Input Validation Tests</h2>
    <div style="margin-bottom: 1rem; padding: 0.75rem; border-radius: 4px">
      <strong>Testing:</strong> Required field validation (red border) after blur. Format: HH:MM:SS
    </div>

    <button @click="clearLogs" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; color: white; margin-bottom: 1rem; background-color: #666">
      🧹 Clear Log
    </button>

    <!-- Grid Layout for Examples -->
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; margin-bottom: 1rem">

      <!-- 1. Required Standalone -->
      <div style="border: 1px solid #f44336; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #c62828">1️⃣ Required (Standalone)</h4>
        <ix-time-input
          ref="requiredInput"
          name="req1"
          label="Required Time"
          required
          @valueChange="onValueChange('1️⃣', $event)"
          @focus="onFocus('1️⃣')"
          @blur="onBlur('1️⃣')"
        ></ix-time-input>
        <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
          <button @click="setEmpty('requiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
          <button @click="setValid('requiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
          <button @click="setInvalid('requiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
          <button @click="manualBlur('requiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
          <button @click="clearInput('requiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
        </div>
      </div>

      <!-- 2. Optional Standalone -->
      <div style="border: 1px solid #4caf50; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #2e7d32">2️⃣ Optional (Standalone)</h4>
        <ix-time-input
          ref="optionalInput"
          name="opt1"
          label="Optional Time"
          @valueChange="onValueChange('2️⃣', $event)"
          @focus="onFocus('2️⃣')"
          @blur="onBlur('2️⃣')"
        ></ix-time-input>
        <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
          <button @click="setEmpty('optionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
          <button @click="setValid('optionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
          <button @click="setInvalid('optionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
          <button @click="manualBlur('optionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
          <button @click="clearInput('optionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
        </div>
      </div>

      <!-- 3. Form Required -->
      <div style="border: 1px solid #2196F3; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #1565c0">3️⃣ Required (In Form)</h4>
        <form @submit.prevent="onFormSubmit('3️⃣')">
          <ix-time-input
            ref="formRequiredInput"
            name="formReq"
            label="Required Time"
            required
            @valueChange="onValueChange('3️⃣', $event)"
            @focus="onFocus('3️⃣')"
            @blur="onBlur('3️⃣')"
          ></ix-time-input>
          <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
            <button type="submit" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #2196F3; color: white">Submit</button>
            <button type="button" @click="setEmpty('formRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
            <button type="button" @click="setValid('formRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
            <button type="button" @click="setInvalid('formRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
            <button type="button" @click="manualBlur('formRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
            <button type="button" @click="clearInput('formRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
          </div>
        </form>
      </div>

      <!-- 4. Form Optional -->
      <div style="border: 1px solid #009688; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #00695c">4️⃣ Optional (In Form)</h4>
        <form @submit.prevent="onFormSubmit('4️⃣')">
          <ix-time-input
            ref="formOptionalInput"
            name="formOpt"
            label="Optional Time"
            @valueChange="onValueChange('4️⃣', $event)"
            @focus="onFocus('4️⃣')"
            @blur="onBlur('4️⃣')"
          ></ix-time-input>
          <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
            <button type="submit" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #2196F3; color: white">Submit</button>
            <button type="button" @click="setEmpty('formOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
            <button type="button" @click="setValid('formOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
            <button type="button" @click="setInvalid('formOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
            <button type="button" @click="manualBlur('formOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
            <button type="button" @click="clearInput('formOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
          </div>
        </form>
      </div>

      <!-- 5. NoValidate Required -->
      <div style="border: 1px solid #ff9800; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #e65100">5️⃣ Required (NoValidate Form)</h4>
        <form novalidate @submit.prevent="onFormSubmit('5️⃣')">
          <ix-time-input
            ref="noValidateRequiredInput"
            name="noValReq"
            label="Required Time"
            required
            @valueChange="onValueChange('5️⃣', $event)"
            @focus="onFocus('5️⃣')"
            @blur="onBlur('5️⃣')"
          ></ix-time-input>
          <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
            <button type="submit" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #2196F3; color: white">Submit</button>
            <button type="button" @click="setEmpty('noValidateRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
            <button type="button" @click="setValid('noValidateRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
            <button type="button" @click="setInvalid('noValidateRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
            <button type="button" @click="manualBlur('noValidateRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
            <button type="button" @click="clearInput('noValidateRequiredInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
          </div>
        </form>
      </div>

      <!-- 6. NoValidate Optional -->
      <div style="border: 1px solid #9c27b0; padding: 1rem; border-radius: 4px">
        <h4 style="margin: 0 0 0.5rem 0; color: #6a1b9a">6️⃣ Optional (NoValidate Form)</h4>
        <form novalidate @submit.prevent="onFormSubmit('6️⃣')">
          <ix-time-input
            ref="noValidateOptionalInput"
            name="noValOpt"
            label="Optional Time"
            @valueChange="onValueChange('6️⃣', $event)"
            @focus="onFocus('6️⃣')"
            @blur="onBlur('6️⃣')"
          ></ix-time-input>
          <div style="display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap">
            <button type="submit" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #2196F3; color: white">Submit</button>
            <button type="button" @click="setEmpty('noValidateOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #757575; color: white">Empty</button>
            <button type="button" @click="setValid('noValidateOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #4caf50; color: white">Valid</button>
            <button type="button" @click="setInvalid('noValidateOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff9800; color: white">Invalid</button>
            <button type="button" @click="manualBlur('noValidateOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #ff5722; color: white">Manual Blur</button>
            <button type="button" @click="clearInput('noValidateOptionalInput')" style="padding: 0.4rem 0.8rem; font-size: 0.85rem; border: none; border-radius: 4px; cursor: pointer; background-color: #9c27b0; color: white">Clear()</button>
          </div>
        </form>
      </div>

    </div>

    <!-- Event Log -->
    <div style="margin-top: 1rem">
      <h3 style="margin-bottom: 0.5rem">Event Log</h3>
      <div style="height: 200px; overflow-y: auto; border: 1px solid #ccc; padding: 0.5rem; background: #f9f9f9; border-radius: 4px">
        <div
          v-for="log in logs"
          :key="log.id"
          style="font-family: monospace; font-size: 0.8rem; margin-bottom: 0.25rem; padding: 0.25rem; background: white; border-radius: 2px"
        >
          {{ log.message }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, nextTick } from 'vue';

interface LogEntry {
  id: string;
  message: string;
}

const logs = ref<LogEntry[]>([]);
let logIdCounter = 0;

// Refs for the inputs
const requiredInput = ref();
const optionalInput = ref();
const formRequiredInput = ref();
const formOptionalInput = ref();
const noValidateRequiredInput = ref();
const noValidateOptionalInput = ref();

const addLog = (message: string) => {
  logIdCounter += 1;
  const uniqueId = `${Date.now()}-${logIdCounter}`;
  logs.value.push({
    id: uniqueId,
    message: `[${new Date().toLocaleTimeString()}] ${message}`
  });
};

const clearLogs = () => {
  logs.value = [];
  addLog('🧹 Logs cleared');
};

const onValueChange = (prefix: string, event: any) => {
  addLog(`${prefix} Value: "${event.detail ?? 'empty'}"`);
};

const onFocus = (prefix: string) => {
  addLog(`${prefix} Focus`);
};

const onBlur = (prefix: string) => {
  addLog(`${prefix} Blur`);
};

const onFormSubmit = (prefix: string) => {
  addLog(`${prefix} Form submitted`);
};

const getInputRef = (refName: string) => {
  const refs = {
    requiredInput: requiredInput.value,
    optionalInput: optionalInput.value,
    formRequiredInput: formRequiredInput.value,
    formOptionalInput: formOptionalInput.value,
    noValidateRequiredInput: noValidateRequiredInput.value,
    noValidateOptionalInput: noValidateOptionalInput.value,
  };
  return refs[refName as keyof typeof refs];
};

const setEmpty = async (refName: string) => {
  const input = getInputRef(refName);
  if (input) {
    input.value = '';
    addLog(`${refName} set to empty`);
  }
};

const setValid = async (refName: string) => {
  const input = getInputRef(refName);
  if (input) {
    input.value = '14:30:00';
    addLog(`${refName} set to valid time`);
  }
};

const setInvalid = async (refName: string) => {
  const input = getInputRef(refName);
  if (input) {
    input.value = 'invalid';
    addLog(`${refName} set to invalid`);
  }
};

const manualBlur = async (refName: string) => {
  const input = getInputRef(refName);
  if (input) {
    try {
      const nativeInput = await input.getNativeInputElement();
      if (nativeInput) {
        nativeInput.dispatchEvent(new FocusEvent('blur', { bubbles: true }));
        addLog(`${refName} manual blur triggered`);
      }
    } catch (error) {
      addLog(`${refName} manual blur failed: ${error}`);
    }
  }
};

const clearInput = async (refName: string) => {
  const input = getInputRef(refName);
  if (input && typeof input.clear === 'function') {
    await input.clear();
    addLog(`${refName} clear() method called`);
  } else {
    addLog(`${refName} clear() method not available`);
  }
};
</script>

// packages/angular-test-app/src/preview-examples/time-input-form-test.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  standalone: false,
  selector: 'app-example',
  templateUrl: './time-input-form-test.html',
})
export default class TimeInputFormTest implements AfterViewInit {
  @ViewChild('requiredInput') requiredInput!: ElementRef;
  @ViewChild('optionalInput') optionalInput!: ElementRef;
  @ViewChild('formRequiredInput') formRequiredInput!: ElementRef;
  @ViewChild('rangeStartInput') rangeStartInput!: ElementRef;
  @ViewChild('rangeEndInput') rangeEndInput!: ElementRef;

  logs: string[] = [];
  testForm: FormGroup;

  constructor(private readonly fb: FormBuilder) {
    this.testForm = this.fb.group({
      requiredTime: ['', Validators.required],
      optionalTime: ['']
    });
  }

  ngAfterViewInit(): void {
    this.addLog('🔧 Component initialized with ViewChild references');
  }

  onValueChange(event: CustomEvent, emoji: string): void {
    const value = event.detail;
    this.addLog(`${emoji} Value changed: ${value || 'empty'}`);
  }

  onFocus(emoji: string): void {
    this.addLog(`${emoji} 🔍 Focus`);
  }

  onBlur(emoji: string): void {
    this.addLog(`${emoji} 😴 Blur`);
  }

  onFormSubmit(event: Event, emoji: string): void {
    event.preventDefault();
    this.addLog(`${emoji} Form submitted`);
    this.addLog(`Form valid: ${this.testForm.valid}`);
    this.addLog(`Form values: ${JSON.stringify(this.testForm.value)}`);
  }

  addLog(message: string): void {
    const timestamp = new Date().toLocaleTimeString();
    this.logs.push(`[${timestamp}] ${message}`);
    if (this.logs.length > 50) {
      this.logs = this.logs.slice(-50);
    }
  }

  clearLogs(): void {
    this.addLog('🧹 Clear logs button clicked');
    this.logs = [];
  }

  setEmpty(inputComponent: any, emoji: string): void {
    this.addLog(`${emoji} 🔘 Empty button clicked`);
    try {
      const element = inputComponent?.nativeElement;
      
      if (element) {
        // Method 1: Set value and dispatch events to trigger validation
        element.value = '';
        
        // Trigger input event to notify the component of value change
        element.dispatchEvent(new Event('input', { bubbles: true }));
        
        // Trigger change event for additional validation clearing
        element.dispatchEvent(new Event('change', { bubbles: true }));
        
        // Trigger blur to ensure validation state updates
        setTimeout(() => {
          element.dispatchEvent(new Event('blur', { bubbles: true }));
        }, 10);
        
        this.addLog(`${emoji} Cleared via nativeElement with events`);
        
        // Method 2: Try component-specific clear method if available
        if (inputComponent.clear && typeof inputComponent.clear === 'function') {
          inputComponent.clear();
          this.addLog(`${emoji} Also called component.clear()`);
        }
        
        // Method 3: Try setting component value property
        if (inputComponent.value !== undefined) {
          inputComponent.value = '';
          this.addLog(`${emoji} Also set component.value`);
        }
        
      } else if (inputComponent?.value !== undefined) {
        inputComponent.value = '';
        this.addLog(`${emoji} Set via component.value`);
      } else {
        this.addLog(`${emoji} ❌ Could not clear - unknown component structure`);
        console.log('Input component:', inputComponent);
      }
    } catch (error) {
      this.addLog(`${emoji} ❌ Error clearing input: ${error}`);
    }
  }

  setValid(inputComponent: any, emoji: string): void {
    this.addLog(`${emoji} ✅ Valid button clicked`);
    try {
      const validTime = '14:30:00';
      if (inputComponent?.nativeElement) {
        inputComponent.nativeElement.value = validTime;
        this.addLog(`${emoji} Set via nativeElement.value: ${validTime}`);
      } else if (inputComponent?.value !== undefined) {
        inputComponent.value = validTime;
        this.addLog(`${emoji} Set via component.value: ${validTime}`);
      } else {
        this.addLog(`${emoji} ❌ Could not set valid time - unknown component structure`);
        console.log('Input component:', inputComponent);
      }
    } catch (error) {
      this.addLog(`${emoji} ❌ Error setting valid time: ${error}`);
    }
  }

  setInvalid(inputComponent: any, emoji: string): void {
    this.addLog(`${emoji} ❌ Invalid button clicked`);
    try {
      const invalidTime = '25:99:99';
      if (inputComponent?.nativeElement) {
        inputComponent.nativeElement.value = invalidTime;
        this.addLog(`${emoji} Set via nativeElement.value: ${invalidTime}`);
      } else if (inputComponent?.value !== undefined) {
        inputComponent.value = invalidTime;
        this.addLog(`${emoji} Set via component.value: ${invalidTime}`);
      } else {
        this.addLog(`${emoji} ❌ Could not set invalid time - unknown component structure`);
        console.log('Input component:', inputComponent);
      }
    } catch (error) {
      this.addLog(`${emoji} ❌ Error setting invalid time: ${error}`);
    }
  }

  triggerManualBlur(inputComponent: any, emoji: string): void {
    this.addLog(`${emoji} 🔶 Manual blur button clicked`);
    try {
      if (inputComponent?.nativeElement?.blur) {
        inputComponent.nativeElement.blur();
        this.addLog(`${emoji} Blur triggered via nativeElement.blur()`);
      } else if (inputComponent?.blur) {
        inputComponent.blur();
        this.addLog(`${emoji} Blur triggered via component.blur()`);
      } else {
        this.addLog(`${emoji} ❌ Could not trigger blur - no blur method found`);
        console.log('Input component:', inputComponent);
      }
    } catch (error) {
      this.addLog(`${emoji} ❌ Error triggering blur: ${error}`);
    }
  }

  clearInput(inputComponent: any, emoji: string): void {
    this.addLog(`${emoji} 🧹 Clear button clicked`);
    
    try {
      // Method 1: Try to call the IX component's internal clear method first
      if (inputComponent && typeof inputComponent.clear === 'function') {
        inputComponent.clear();
        this.addLog(`${emoji} ✅ Called IX component.clear() method`);
      } else {
        this.addLog(`${emoji} ⚠️ No clear() method found on IX component`);
      }
      
      // Method 2: Try calling clear on the native element if it exists
      const element = inputComponent?.nativeElement;
      if (element && typeof element.clear === 'function') {
        element.clear();
        this.addLog(`${emoji} ✅ Called nativeElement.clear() method`);
      } else {
        this.addLog(`${emoji} ⚠️ No clear() method found on native element`);
      }
      
      // Method 3: Fallback to setEmpty which sets value and triggers events
      this.setEmpty(inputComponent, emoji);
      
      // Method 4: Force validation update by triggering focus and blur
      setTimeout(() => {
        if (element && element.focus && element.blur) {
          element.focus();
          setTimeout(() => element.blur(), 10);
          this.addLog(`${emoji} 🔄 Triggered focus/blur for validation update`);
        }
      }, 20);
      
    } catch (error) {
      this.addLog(`${emoji} ❌ Error in clearInput: ${error}`);
      // Fallback to setEmpty if there's an error
      this.setEmpty(inputComponent, emoji);
    }
  }

  setTimeRange(): void {
    this.addLog('4️⃣ ⏰ Setting work hours (9:00 - 17:00)');
    try {
      if (this.rangeStartInput?.nativeElement) {
        this.rangeStartInput.nativeElement.value = '09:00:00';
        this.addLog('4️⃣ Start time set to 9:00 AM');
      }
      if (this.rangeEndInput?.nativeElement) {
        this.rangeEndInput.nativeElement.value = '17:00:00';
        this.addLog('4️⃣ End time set to 5:00 PM');
      }
    } catch (error) {
      this.addLog(`4️⃣ ❌ Error setting work hours: ${error}`);
    }
  }

  setMeetingTimes(): void {
    this.addLog('4️⃣ 📅 Setting meeting times (14:00 - 15:30)');
    try {
      if (this.rangeStartInput?.nativeElement) {
        this.rangeStartInput.nativeElement.value = '14:00:00';
        this.addLog('4️⃣ Meeting start: 2:00 PM');
      }
      if (this.rangeEndInput?.nativeElement) {
        this.rangeEndInput.nativeElement.value = '15:30:00';
        this.addLog('4️⃣ Meeting end: 3:30 PM');
      }
    } catch (error) {
      this.addLog(`4️⃣ ❌ Error setting meeting times: ${error}`);
    }
  }

  setCurrentTime(): void {
    this.addLog('4️⃣ 🕐 Setting current time');
    try {
      const now = new Date();
      const timeString = now.toTimeString().split(' ')[0]; // Gets HH:MM:SS
      if (this.rangeStartInput?.nativeElement) {
        this.rangeStartInput.nativeElement.value = timeString;
        this.addLog(`4️⃣ Current time set: ${timeString}`);
      }
    } catch (error) {
      this.addLog(`4️⃣ ❌ Error setting current time: ${error}`);
    }
  }

  getLogColor(log: string): string {
    if (log.includes('❌')) return '#f44336';
    if (log.includes('✅')) return '#4caf50';
    if (log.includes('🔍')) return '#2196f3';
    if (log.includes('😴')) return '#ff9800';
    if (log.includes('⚠️')) return '#ff5722';
    return '#333';
  }
}
