// packages/react-test-app/src/preview-examples/toggle-custom-disable.tsx
/**
 * COPYRIGHT (c) Siemens AG
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
import { IxToggle } from '@siemens/ix-react';
import React from 'react';

export const ToggleDisabled: React.FC = () => {
  return <IxToggle disabled />;
};

// packages/angular-test-app/src/preview-examples/toggle-custom-disable.ts
/**
 * COPYRIGHT (c) Siemens AG
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
import { Component } from '@angular/core';

@Component({
  selector: 'app-toggle-custom-disabled',
  template: ` <ix-toggle disabled></ix-toggle> `,
})
export class ToggleCustomDisabled {}
