// version-dev/auto-generated/previews/react/avatar-initials.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxAvatar } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return <IxAvatar initials="JD"></IxAvatar>;
};

// demo/v2/vue/avatar-initials.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxAvatar } from '@siemens/ix-vue';
</script>

<template>
  <IxAvatar initials="JD"></IxAvatar>
</template>
