// packages/vue-test-app/src/preview-examples/application-advanced.vue
<!--
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import {
  IxApplication,
  IxApplicationHeader,
  IxAvatar,
  IxContent,
  IxContentHeader,
  IxMenu,
  IxMenuAbout,
  IxMenuCategory,
  IxMenuItem,
  IxMenuSettings,
} from '@siemens/ix-vue';
import {
  iconAlarmBell,
  iconHome,
  iconPiechart,
  iconPlant,
  iconNetworkDevice,
} from '@siemens/ix-icons/icons';
import { ref } from 'vue';

const activeContent = ref('home');
</script>

<template>
  <IxApplication>
    <IxApplicationHeader name="My Application">
      <div class="placeholder-logo" slot="logo"></div>
      <IxAvatar username="Example User" extra="Additional info"></IxAvatar>
    </IxApplicationHeader>

    <IxMenu>
      <IxMenuItem
        home
        :icon="iconHome"
        :active="activeContent === 'home'"
        @click="activeContent = 'home'"
        >Home</IxMenuItem
      >
      <IxMenuItem
        :icon="iconAlarmBell"
        :active="activeContent === 'alarm'"
        @click="activeContent = 'alarm'"
        >Alarm</IxMenuItem
      >
      <IxMenuCategory :icon="iconPiechart" label="Analysis">
        <IxMenuItem
          :icon="iconPlant"
          :active="activeContent === 'plant'"
          @click="activeContent = 'plant'"
          >Plant</IxMenuItem
        >
        <IxMenuItem
          :icon="iconNetworkDevice"
          :active="activeContent === 'network'"
          @click="activeContent = 'network'"
          >Network</IxMenuItem
        >
      </IxMenuCategory>
      <IxMenuSettings></IxMenuSettings>
      <IxMenuAbout></IxMenuAbout>
    </IxMenu>
    <IxContent>
      <div v-if="activeContent === 'home'">
        <IxContentHeader header-title="Example home content"></IxContentHeader>
      </div>
      <div v-if="activeContent === 'alarm'">
        <IxContentHeader header-title="Example alarm content"></IxContentHeader>
      </div>
      <div v-if="activeContent === 'plant'">
        <IxContentHeader header-title="Example plant content"></IxContentHeader>
      </div>
      <div v-if="activeContent === 'network'">
        <IxContentHeader
          header-title="Example network content"
        ></IxContentHeader>
      </div>
    </IxContent>
  </IxApplication>
</template>

// packages/react-test-app/src/preview-examples/application-advanced.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  IxApplication,
  IxApplicationHeader,
  IxAvatar,
  IxContent,
  IxContentHeader,
  IxMenu,
  IxMenuAbout,
  IxMenuCategory,
  IxMenuItem,
  IxMenuSettings,
} from '@siemens/ix-react';
import {
  iconAlarmBell,
  iconHome,
  iconPiechart,
  iconPlant,
  iconNetworkDevice,
} from '@siemens/ix-icons/icons';
import { useState } from 'react';

export default () => {
  const [activeContent, setActiveContent] = useState('home');

  return (
    <IxApplication>
      <IxApplicationHeader name="My Application">
        <div className="placeholder-logo" slot="logo"></div>
        <IxAvatar username="Example User" extra="Additional info"></IxAvatar>
      </IxApplicationHeader>

      <IxMenu>
        <IxMenuItem
          home
          icon={iconHome}
          onClick={() => setActiveContent('home')}
          active={activeContent === 'home'}
        >
          Home
        </IxMenuItem>
        <IxMenuItem
          icon={iconAlarmBell}
          onClick={() => setActiveContent('alarm')}
          active={activeContent === 'alarm'}
        >
          Alarm
        </IxMenuItem>
        <IxMenuCategory icon={iconPiechart} label="Analysis">
          <IxMenuItem
            icon={iconPlant}
            onClick={() => setActiveContent('plant')}
            active={activeContent === 'plant'}
          >
            Plant
          </IxMenuItem>
          <IxMenuItem
            icon={iconNetworkDevice}
            onClick={() => setActiveContent('network')}
            active={activeContent === 'network'}
          >
            Network
          </IxMenuItem>
        </IxMenuCategory>
        <IxMenuSettings></IxMenuSettings>
        <IxMenuAbout></IxMenuAbout>
      </IxMenu>
      <IxContent>
        {activeContent === 'home' && (
          <IxContentHeader headerTitle="Example home content"></IxContentHeader>
        )}
        {activeContent === 'alarm' && (
          <IxContentHeader headerTitle="Example alarm content"></IxContentHeader>
        )}
        {activeContent === 'plant' && (
          <IxContentHeader headerTitle="Example plant content"></IxContentHeader>
        )}
        {activeContent === 'network' && (
          <IxContentHeader headerTitle="Example network content"></IxContentHeader>
        )}
      </IxContent>
    </IxApplication>
  );
};
