// packages/angular-test-app/src/preview-examples/button-danger.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: buttonGrey(),
})
export default class Buttons {}
function buttonGrey(): string | undefined {
  return `
      <ix-button class="m-1" variant="danger">
        Button
      </ix-button>
      <ix-button class="m-1" disabled variant="danger">
        Button
      </ix-button>
  `;
}

// packages/react-test-app/src/preview-examples/button-danger.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxButton } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <>
      <IxButton class="m-1" variant="danger">
        Button
      </IxButton>
      <IxButton class="m-1" disabled variant="danger">
        Button
      </IxButton>
    </>
  );
};
