// examples/vue-examples/src/preview-examples/button-danger-primary.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton } from '@siemens/ix-vue';
</script>

<style scoped src="./button-danger-primary.css"></style>

<template>
  <IxButton variant="danger-primary"> Button </IxButton>
  <IxButton disabled variant="danger-primary"> Button </IxButton>
</template>

// packages/react-test-app/src/preview-examples/button-danger-primary.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './button-danger-primary.scoped.css';

import { IxButton } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxButton variant="danger-primary">Button</IxButton>
      <IxButton disabled variant="danger-primary">
        Button
      </IxButton>
    </>
  );
};
