// packages/vue-test-app/src/preview-examples/button-secondary.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxButton } from '@siemens/ix-vue';
</script>

<template>
  <IxButton class="m-1" outline variant="primary"> Button </IxButton>
  <IxButton class="m-1" disabled outline variant="primary"> Button </IxButton>
</template>

// packages/react-test-app/src/preview-examples/button-secondary.tsx
/*
 * SPDX-FileCopyrightText: 2022 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxButton } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <>
      <IxButton class="m-1" outline variant="Primary">
        Button
      </IxButton>
      <IxButton class="m-1" disabled outline variant="Primary">
        Button
      </IxButton>
    </>
  );
};
