// packages/vue-test-app/src/preview-examples/form-checkbox-validation.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxCheckbox, IxCheckboxGroup } from '@siemens/ix-vue';
</script>

<template>
  <div>
    <IxCheckboxGroup
      label="Terms of something"
      info-text="Info text"
      class="ix-info"
    >
      <IxCheckbox label="I agree everything" name="agreed"></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div>
    <IxCheckboxGroup
      label="Terms of something"
      warning-text="Warning text"
      class="ix-warning"
    >
      <IxCheckbox label="I agree everything" name="agreed"></IxCheckbox>
      <IxCheckbox label="I disagree everything" name="agreed"></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div>
    <IxCheckboxGroup
      label="Terms of something"
      valid-text="Invalid text"
      class="ix-invalid"
    >
      <IxCheckbox label="I agree everything" name="agreed"></IxCheckbox>
      <IxCheckbox label="I disagree everything" name="agreed"></IxCheckbox>
    </IxCheckboxGroup>
  </div>

  <div>
    <IxCheckboxGroup
      label="Terms of something"
      valid-text="Valid text"
      class="ix-valid"
    >
      <IxCheckbox label="I agree everything" name="agreed"></IxCheckbox>
      <IxCheckbox label="I disagree everything" name="agreed"></IxCheckbox>
    </IxCheckboxGroup>
  </div>
</template>

// packages/react-test-app/src/preview-examples/form-checkbox-validation.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxCheckbox, IxCheckboxGroup } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <div>
        <IxCheckboxGroup label="Terms of something" infoText="Info text">
          <IxCheckbox
            label="I agree everything"
            name="agreed"
            className="ix-info"
          ></IxCheckbox>
        </IxCheckboxGroup>
      </div>

      <div>
        <IxCheckboxGroup label="Terms of something" warningText="Warning text">
          <IxCheckbox
            label="I agree everything"
            name="agreed"
            className="ix-warning"
          ></IxCheckbox>
          <IxCheckbox
            label="I disagree everything"
            name="agreed"
            className="ix-warning"
          ></IxCheckbox>
        </IxCheckboxGroup>
      </div>

      <div>
        <IxCheckboxGroup label="Terms of something" invalidText="Invalid text">
          <IxCheckbox
            label="I agree everything"
            name="agreed"
            className="ix-invalid"
          ></IxCheckbox>
          <IxCheckbox
            label="I disagree everything"
            name="agreed"
            className="ix-invalid"
          ></IxCheckbox>
        </IxCheckboxGroup>
      </div>

      <div>
        <IxCheckboxGroup label="Terms of something" validText="Valid text">
          <IxCheckbox
            label="I agree everything"
            name="agreed"
            className="ix-valid"
          ></IxCheckbox>
          <IxCheckbox
            label="I disagree everything"
            name="agreed"
            className="ix-valid"
          ></IxCheckbox>
        </IxCheckboxGroup>
      </div>
    </>
  );
};
