// packages/vue-test-app/src/preview-examples/generic-list-variants.vue
<!--
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxList, IxListItem } from '@siemens/ix-vue';
import { addIcons } from '@siemens/ix-icons';
import { iconProject } from '@siemens/ix-icons/icons';

addIcons({ iconProject });
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 24px">
    <IxList divider item-gap="none" variant="ghost">
      <IxListItem icon="project" label="Item 1"></IxListItem>
      <IxListItem icon="project" label="Item 2"></IxListItem>
      <IxListItem icon="project" label="Item 3" divider="false"></IxListItem>
    </IxList>
    <IxList variant="outline" item-gap="sm">
      <IxListItem icon="project" label="Item 1"></IxListItem>
      <IxListItem icon="project" label="Item 2"></IxListItem>
      <IxListItem icon="project" label="Item 3"></IxListItem>
    </IxList>
    <IxList variant="filled">
      <IxListItem icon="project" label="Item 1"></IxListItem>
      <IxListItem icon="project" label="Item 2"></IxListItem>
      <IxListItem icon="project" label="Item 3"></IxListItem>
    </IxList>
  </div>
</template>

// packages/react-test-app/src/preview-examples/generic-list-variants.tsx
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxList, IxListItem } from '@siemens/ix-react';
import { addIcons } from '@siemens/ix-icons';
import { iconProject } from '@siemens/ix-icons/icons';

export default function GenericListVariants() {
  addIcons({ iconProject });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <IxList divider itemGap="none" variant="ghost">
        <IxListItem icon="project" label="Item 1"></IxListItem>
        <IxListItem icon="project" label="Item 2"></IxListItem>
        <IxListItem icon="project" label="Item 3" divider={false}></IxListItem>
      </IxList>
      <IxList variant="outline" itemGap="sm">
        <IxListItem icon="project" label="Item 1"></IxListItem>
        <IxListItem icon="project" label="Item 2"></IxListItem>
        <IxListItem icon="project" label="Item 3"></IxListItem>
      </IxList>
      <IxList variant="filled">
        <IxListItem icon="project" label="Item 1"></IxListItem>
        <IxListItem icon="project" label="Item 2"></IxListItem>
        <IxListItem icon="project" label="Item 3"></IxListItem>
      </IxList>
    </div>
  );
}
