// packages/vue-test-app/src/preview-examples/modal-form-ix-button-submit.vue
<script setup lang="ts">
import {
  HTMLRefElement,
  IxButton,
  IxModalHeader,
  IxModalContent,
  IxModalFooter,
  IxInput,
} from '@siemens/ix-vue';
import { ref } from 'vue';

const modalRef = ref<HTMLRefElement<HTMLIxModalElement>>();
const show = ref(false);

const close = () => {
  modalRef.value?.$el.closeModal('close payload!');
  show.value = false;
};

const dismiss = () => {
  modalRef.value?.$el.dismissModal('dismiss payload');
  show.value = false;
};

const submitForm = (event: Event) => {
  event.preventDefault();
  console.log('Form submitted successfully');
  close();
};
</script>

<template>
  <IxButton @click="show = true">Show modal</IxButton>

  <IxDialog ref="modalRef" v-if="show">
    <IxModalHeader @closeClick="dismiss">Create Resource</IxModalHeader>

    <IxModalContent>
      <form id="create-resource-form" @submit="submitForm">
        <div class="form-group">
          <IxInput
            label="Name"
            type="text"
            class="form-control"
            id="name"
            name="name"
          ></IxInput>
        </div>
      </form>
    </IxModalContent>

    <IxModalFooter>
      <IxButton outline @click="dismiss">Cancel</IxButton>
      <IxButton form="create-resource-form" type="submit">Submit</IxButton>
    </IxModalFooter>
  </IxDialog>
</template>

// packages/react-test-app/src/preview-examples/modal-form-ix-button-submit.tsx
import {
  IxButton,
  IxModalContent,
  IxModalFooter,
  IxModalHeader,
  Modal,
  ModalRef,
  showModal,
  IxInput,
} from '@siemens/ix-react';
import { useRef } from 'react';

function CustomModal() {
  const modalRef = useRef<ModalRef>(null);

  const close = () => {
    modalRef.current?.close('close payload!');
  };
  const dismiss = () => {
    modalRef.current?.dismiss('dismiss payload');
  };

  return (
    <Modal ref={modalRef}>
      <IxModalHeader onCloseClick={() => dismiss()}>
        Create Resource
      </IxModalHeader>
      <IxModalContent>
        <form
          id="create-resource-form"
          onSubmit={(e) => {
            e.preventDefault();
            console.log('Form submitted successfully');
            close();
          }}
        >
          <div className="form-group">
            <IxInput
              label="Name"
              type="text"
              className="form-control"
              id="name"
              name="name"
            ></IxInput>
          </div>
        </form>
      </IxModalContent>
      <IxModalFooter>
        <IxButton outline onClick={() => dismiss()}>
          Cancel
        </IxButton>
        <IxButton form="create-resource-form" type="submit">
          Submit
        </IxButton>
      </IxModalFooter>
    </Modal>
  );
}

export default () => {
  async function show() {
    await showModal({
      content: <CustomModal />,
    });
  }

  return <IxButton onClick={show}>Show modal</IxButton>;
};
