// packages/angular-test-app/src/preview-examples/number-field-disabled.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  templateUrl: './number-field-disabled.html'
})
export default class NumberFieldDisabled {}

// packages/react-test-app/src/preview-examples/number-field-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberField } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxNumberField disabled></IxNumberField>
    </>
  );
};
