// packages/vue-test-app/src/preview-examples/number-field-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxNumberField } from '@siemens/ix-vue';
</script>

<template>
  <IxNumberField disabled></IxNumberField>
</template>

// packages/react-test-app/src/preview-examples/number-field-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberField } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxNumberField disabled></IxNumberField>
    </>
  );
};
