// feat/block-cli/examples/angular-standalone-examples/src/preview-examples/number-input-disabled.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxNumberInput,
  IxTextValueAccessorDirective,
} from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxNumberInput, IxTextValueAccessorDirective],
  templateUrl: './number-input-disabled.html',
})
export default class NumberInputDisabled {}

// packages/react-test-app/src/preview-examples/number-input-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxNumberInput } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxNumberInput disabled></IxNumberInput>
    </>
  );
};
