// packages/vue-test-app/src/preview-examples/progress-bar-variants.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxProgressBar } from '@siemens/ix-vue';
</script>

<template>
    <IxProgressBar value="50" variant='primary'></IxProgressBar>

    <IxProgressBar value="50" variant='alarm'></IxProgressBar>

    <IxProgressBar value="50" variant='critical'></IxProgressBar>

    <IxProgressBar value="50" variant='warning'></IxProgressBar>

    <IxProgressBar value="50" variant='info'></IxProgressBar>

    <IxProgressBar value="50" variant='neutral'></IxProgressBar>

    <IxProgressBar value="50" variant='success'></IxProgressBar>
</template>

// packages/react-test-app/src/preview-examples/progress-bar-variants.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxProgressBar } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <>
      <IxProgressBar value={50} variant='primary'></IxProgressBar>

      <IxProgressBar value={50} variant='alarm'></IxProgressBar>

      <IxProgressBar value={50} variant='critical'></IxProgressBar>

      <IxProgressBar value={50} variant='warning'></IxProgressBar>

      <IxProgressBar value={50} variant='info'></IxProgressBar>

      <IxProgressBar value={50} variant='neutral'></IxProgressBar>

      <IxProgressBar value={50} variant='success'></IxProgressBar>
    </>
  );
};
