// packages/vue-test-app/src/preview-examples/side-pane-group-inline.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import {
  IxButton,
  IxSidePane,
  IxSidePaneContentArea,
  IxSidePaneGroup,
} from '@siemens/ix-vue';
</script>

<template>
  <IxSidePaneGroup floating variant="1">
    <IxSidePane paneTitle="TOP" slot="top"></IxSidePane>
    <IxSidePane paneTitle="RIGHT" slot="right"></IxSidePane>
    <IxSidePane ref="leftSidePane" paneTitle="LEFT" slot="left"></IxSidePane>
    <IxSidePane paneTitle="BOTTOM" slot="bottom"></IxSidePane>
    <IxSidePaneContentArea slot="content">
      <IxButton @click="handleButtonClick"> Toggle left pane</IxButton>
    </IxSidePaneContentArea>
  </IxSidePaneGroup>
</template>

// packages/react-test-app/src/preview-examples/side-pane-group-inline.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  IxSidePane,
  IxSidePaneContentArea,
  IxSidePaneGroup,
} from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <IxSidePaneGroup inline>
      <IxSidePane paneTitle="TOP" slot="top"></IxSidePane>
      <IxSidePane paneTitle="RIGHT" slot="right"></IxSidePane>
      <IxSidePane paneTitle="LEFT" slot="left"></IxSidePane>
      <IxSidePane paneTitle="BOTTOM" slot="bottom"></IxSidePane>
      <IxSidePaneContentArea slot="content">
        <p>This is a text content.</p>
      </IxSidePaneContentArea>
    </IxSidePaneGroup>
  );
};
