// packages/ix-documentation/static/auto-generated/previews/angular/spinner.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: ` <ix-spinner></ix-spinner> `,
})
export default class Spinner {}

// packages/react-test-app/src/preview-examples/spinner.tsx
/*
 * SPDX-FileCopyrightText: 2022 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxSpinner } from '@siemens/ix-react';
import React from 'react';

export const Spinner: React.FC = () => {
  return <IxSpinner></IxSpinner>;
};
