// packages/vue-test-app/src/preview-examples/text-field-disabled.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang='ts'>
import { IxTextField } from '@siemens/ix-vue';

</script>

<template>
  <div>
    <IxTextField
      placeholder="Some placeholder"
      value="Some example text"
      disabled
    ></IxTextField>
  </div>
</template>

// packages/react-test-app/src/preview-examples/text-field-disabled.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTextField } from '@siemens/ix-react';

export default () => {
  return (
    <>
      <IxTextField
        placeholder="Some placeholder"
        value="Some example text"
        disabled
      ></IxTextField>
    </>
  );
};
