// packages/vue-test-app/src/preview-examples/toggle-button-primary-ghost.vue
<!--
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxToggleButton } from '@siemens/ix-vue';
</script>

<template>
  <IxToggleButton className="m-1" variant="primary" ghost>Normal</IxToggleButton>
  <IxToggleButton className="m-1" variant="primary" ghost>Pressed</IxToggleButton>
  <IxToggleButton className="m-1" variant="primary" ghost>Disabled</IxToggleButton>
  <IxToggleButton className="m-1" variant="primary" ghost>Loading</IxToggleButton>
</template>

// packages/react-test-app/src/preview-examples/toggle-button-primary-ghost.tsx
/*
 * SPDX-FileCopyrightText: 2023 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggleButton } from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <>
      <IxToggleButton variant="primary" ghost outline={false} className="m-1">
        Normal
      </IxToggleButton>
      <IxToggleButton variant="primary" ghost outline={false} pressed className="m-1">
        Pressed
      </IxToggleButton>
      <IxToggleButton variant="primary" ghost outline={false} className="m-1" disabled>
        Disabled
      </IxToggleButton>
      <IxToggleButton variant="primary" ghost outline={false} className="m-1" disabled loading>
        Loading
      </IxToggleButton>
    </>
  );
};
