// packages/angular-test-app/src/preview-examples/toggle-color.ts
/*
 * SPDX-FileCopyrightText: 2022 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-toggle-color',
  template: ` <ix-toggle color="warning"></ix-toggle> `,
})
export class ToggleColor {}

// packages/react-test-app/src/preview-examples/toggle-color.tsx
/*
 * SPDX-FileCopyrightText: 2022 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxToggle } from '@siemens/ix-react';
import React from 'react';

export const ToggleColor: React.FC = () => {
  return <IxToggle color="warning" />;
};
